packages:
  - 'packages/*'
  - 'examples/*'
  - 'tests/integration/*'

catalog:
  '@cloudflare/workers-types': ^4.20240919.0
  '@types/node': ^22.5.5
  'typescript': ^5.6.2
  'vite': 6.0.0-beta.4
  'vitest': '^2.1.2'
  'wrangler': '^3.80.4'
