packages:
  - 'packages/*'
  - 'examples/*'
  - 'tests/integration/*'

catalog:
  '@cloudflare/workers-types': ^4.20241004.0
  'miniflare': ^3.20241004.0
  'typescript': ^5.6.2
  'vite': '6.0.0-beta.2'
  'vitest': '^2.1.2'
  'wrangler': '^3.80.4'
