name = "server"
main = "./entry.server.tsx"
compatibility_date = "2024-12-05"
compatibility_flags = ["nodejs_compat"]

[durable_objects]
bindings = [{ name = "COUNTER", class_name = "Counter" }]

[[migrations]]
tag = "v1"
new_classes = ["Counter"]
