name = "worker"
main = "./src/index.ts"
compatibility_date = "2024-12-30"

vars = { MY_VAR = "Top level var" }

[env.custom-env]
vars = { MY_VAR = "Custom env var" }

[env.custom-mode]
vars = { MY_VAR = "Custom mode var" }
