// Generated by Wrangler by running `wrangler types -c ./worker-a/wrangler.toml ./worker-a/worker-configuration.d.ts`

interface Env {
	DURABLE_OBJECT: DurableObjectNamespace /* Counter */;
	WORKER_B: Fetcher;
	NAMED_ENTRYPOINT: Fetcher;
}
