compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]

services = [
	{ binding = "WORKER_B", service = "worker_b" },
	{ binding = "NAMED_ENTRYPOINT", service = "worker_b", entrypoint = "NamedEntrypoint" },
]
